
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ARGUMENT ASSIGNMENT COMMENT CONTINUATION FOR INDENT KEYWORD NAME SEPARATOR SETTING SETTING_VALUEtestcases : testcase\n                    | testcases testcasetestcase : NAME\n                    | NAME body_itemsbody_items : body_item\n                      | body_items body_item\n        body_item : forloop\n                     | setting \n                     | step\n        setting : SETTING setting_valuessetting_values : SETTING_VALUE\n                          | setting_values SETTING_VALUEstep : KEYWORD\n                | KEYWORD argumentsstep : assignments KEYWORD\n                | assignments KEYWORD argumentsforloop : FOR arguments foritemsforitems : INDENT step\n                    | foritems INDENT step\n        assignments : ASSIGNMENT\n                     | assignments ASSIGNMENTarguments : ARGUMENT\n                     | arguments ARGUMENT'
    
_lr_action_items = {'FOR':([3,5,10,11,12,13,14,15,16,18,19,21,22,23,24,26,27,29,30,],[7,-7,-9,-8,-13,7,-5,-10,-11,-22,-15,-14,-6,-12,-17,-23,-16,-18,-19,]),'INDENT':([12,17,18,19,21,24,26,27,29,30,],[-13,25,-22,-15,-14,28,-23,-16,-18,-19,]),'NAME':([0,1,2,3,4,5,10,11,12,13,14,15,16,18,19,21,22,23,24,26,27,29,30,],[3,-1,3,-3,-2,-7,-9,-8,-13,-4,-5,-10,-11,-22,-15,-14,-6,-12,-17,-23,-16,-18,-19,]),'KEYWORD':([3,5,8,9,10,11,12,13,14,15,16,18,19,20,21,22,23,24,25,26,27,28,29,30,],[12,-7,-20,19,-9,-8,-13,12,-5,-10,-11,-22,-15,-21,-14,-6,-12,-17,12,-23,-16,12,-18,-19,]),'ASSIGNMENT':([3,5,8,9,10,11,12,13,14,15,16,18,19,20,21,22,23,24,25,26,27,28,29,30,],[8,-7,-20,20,-9,-8,-13,8,-5,-10,-11,-22,-15,-21,-14,-6,-12,-17,8,-23,-16,8,-18,-19,]),'ARGUMENT':([7,12,17,18,19,21,26,27,],[18,18,26,-22,18,26,-23,26,]),'SETTING':([3,5,10,11,12,13,14,15,16,18,19,21,22,23,24,26,27,29,30,],[6,-7,-9,-8,-13,6,-5,-10,-11,-22,-15,-14,-6,-12,-17,-23,-16,-18,-19,]),'SETTING_VALUE':([6,15,16,23,],[16,23,-11,-12,]),'$end':([1,2,3,4,5,10,11,12,13,14,15,16,18,19,21,22,23,24,26,27,29,30,],[-1,0,-3,-2,-7,-9,-8,-13,-4,-5,-10,-11,-22,-15,-14,-6,-12,-17,-23,-16,-18,-19,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'forloop':([3,13,],[5,5,]),'foritems':([17,],[24,]),'setting_values':([6,],[15,]),'step':([3,13,25,28,],[10,10,29,30,]),'testcase':([0,2,],[1,4,]),'assignments':([3,13,25,28,],[9,9,9,9,]),'testcases':([0,],[2,]),'setting':([3,13,],[11,11,]),'arguments':([7,12,19,],[17,21,27,]),'body_items':([3,],[13,]),'body_item':([3,13,],[14,22,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> testcases","S'",1,None,None,None),
  ('testcases -> testcase','testcases',1,'p_testcases','tcukparser.py',65),
  ('testcases -> testcases testcase','testcases',2,'p_testcases','tcukparser.py',66),
  ('testcase -> NAME','testcase',1,'p_testcase','tcukparser.py',70),
  ('testcase -> NAME body_items','testcase',2,'p_testcase','tcukparser.py',71),
  ('body_items -> body_item','body_items',1,'p_body_items','tcukparser.py',78),
  ('body_items -> body_items body_item','body_items',2,'p_body_items','tcukparser.py',79),
  ('body_item -> forloop','body_item',1,'p_body_item','tcukparser.py',94),
  ('body_item -> setting','body_item',1,'p_body_item','tcukparser.py',95),
  ('body_item -> step','body_item',1,'p_body_item','tcukparser.py',96),
  ('setting -> SETTING setting_values','setting',2,'p_setting','tcukparser.py',101),
  ('setting_values -> SETTING_VALUE','setting_values',1,'p_setting_values','tcukparser.py',105),
  ('setting_values -> setting_values SETTING_VALUE','setting_values',2,'p_setting_values','tcukparser.py',106),
  ('step -> KEYWORD','step',1,'p_step','tcukparser.py',110),
  ('step -> KEYWORD arguments','step',2,'p_step','tcukparser.py',111),
  ('step -> assignments KEYWORD','step',2,'p_step_with_assignment','tcukparser.py',118),
  ('step -> assignments KEYWORD arguments','step',3,'p_step_with_assignment','tcukparser.py',119),
  ('forloop -> FOR arguments foritems','forloop',3,'p_forloop','tcukparser.py',126),
  ('foritems -> INDENT step','foritems',2,'p_foritems','tcukparser.py',130),
  ('foritems -> foritems INDENT step','foritems',3,'p_foritems','tcukparser.py',131),
  ('assignments -> ASSIGNMENT','assignments',1,'p_assignments','tcukparser.py',140),
  ('assignments -> assignments ASSIGNMENT','assignments',2,'p_assignments','tcukparser.py',141),
  ('arguments -> ARGUMENT','arguments',1,'p_arguments','tcukparser.py',145),
  ('arguments -> arguments ARGUMENT','arguments',2,'p_arguments','tcukparser.py',146),
]
